### ISSUE TITLE
Problem decoding output in pilotTools.py

### ISSUE THREAD

**Issue by IgorPelevanyuk** [DIRACGrid/Pilot#112]
Today I have tried to integrate a new resource on SunGridEngine. Job agent started, job status changed to Running. After that, it hangs, job on a resource is finished. In error file of the batch I see the following:
Traceback (most recent call last):
  File "dirac-pilot.py", line 66, in <module>
    command.execute()
  File "/tmp/DIRAC_6fagrxpilot/pilotCommands.py", line 917, in execute
    self.__startJobAgent()
  File "/tmp/DIRAC_6fagrxpilot/pilotCommands.py", line 904, in __startJobAgent
    retCode, _output = self.executeAndGetOutput(jobAgent, self.pp.installEnv)
  File "/tmp/DIRAC_6fagrxpilot/pilotTools.py", line 384, in executeAndGetOutput
    outData = _p.stdout.read().decode().strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 5591: ordinal not in range(128)

**Comment by IgorPelevanyuk** [comment]
Noticed that in Pilot2 this string was without decode:
https://github.com/DIRACGrid/DIRAC/blob/ffd3004e859faba683bb5035923980fe8d67c023/WorkloadManagementSystem/PilotAgent/pilotTools.py#L303
Pilot3:
`outData = _p.stdout.read().decode().strip()`
Pilot2
`outData = _p.stdout.read().strip()`

Does this decode necessary? 
Can it be try/except fix?

**Comment by fstagni** [comment]
Hi Igor, the `decode` has been added for python 3 support. Do you know if by chance the resource you are adding is using native python 3?

I might need to read https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte but I won't have time today (after I will be on holiday until next week) and especially no possibility of looking if the fix is correct. Could you, by chance?

**Comment by IgorPelevanyuk** [comment]
> Do you know if by chance the resource you are adding is using native python 3?

There is no Python3 on the work nodes.

Actually the reason I think is the following:
```
$ date
Чт июн 18 14:08:13 MSK 2020
```

The work nodes are configured with Russian localization. So some UNICODE in output may cause this error. I cannot tell which character exactly.

To see that I had change pilot files manually and remove decode(). After that, the jobs run successfully. I think that the following change do no harm, at least in my case: 
```
try:
  outData = _p.stdout.read().decode().strip()
except Exception as e:
  outData = _p.stdout.read().strip()
```

If that is ok, I can make PR.

**Comment by chrisburr** [comment]
Does it work if you use `universal_newlines=True` in the call to `POpen` instead of reading as bytes and then decoding? I think that will make it use the correct locale from the system.

```python
      _p = subprocess.Popen("%s" % cmd, shell=True, env=environDict, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, close_fds=False, universal_newlines=True)

      # standard output
      outData = _p.stdout.read().strip()
```

**Comment by chaen** [comment]
It's all so complicated these string businesses :-(
How about decoding in `utf-8` instead of `ascii` ? if all we are doing is printing the result, and it never really makes it to a db, then no issues. 
We could be even more violent, and decode in `utf8` and convert to `ascii`, ignoring the error. That will result in some data loss, but well... I don't mind not having `Чт июн` on the logoutput

**Comment by chrisburr** [comment]
> How about decoding in utf-8 instead of ascii ?

I think this will crash in the same way if the locale used by the child process is incompatible with UTF-8. I think `universal_newlines=True` (or even `text=True`) will make Python query the system and do the "right" thing i.e. `decode(encoding=locale.getpreferredencoding(False))`.

If this needs to protect against badly configured systems, the `error` argument was only added to `subprocess.Popen` in Python 3 so it'll have to be done by hand with:

```python
outData = _p.stdout.read().decode(encoding=locale.getpreferredencoding(False), error="replace").strip()
```

or as I guess this still has to support Python 2.6 where the keyword arguments aren't supported:
```python
outData = _p.stdout.read().decode(locale.getpreferredencoding(False), "replace").strip()
```

**Comment by fstagni** [comment]
> or as I guess this still has to support Python 2.6 where the keyword arguments aren't supported:

Just answering on this: yes, python 2.6 sadly should still be supported.

**Comment by fstagni** [comment]
@IgorPelevanyuk please try the suggestion given by Chris Burr.

**Comment by IgorPelevanyuk** [comment]
First
------
```
      _p = subprocess.Popen("%s" % cmd, shell=True, env=environDict, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, close_fds=False, universal_newlines=True)
      outData = _p.stdout.read().strip()
```
Without decode() it will work anyway. With decode() - not.

Second
----------

```
_p = subprocess.Popen("%s" % cmd, shell=True, env=environDict, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, close_fds=False, universal_newlines=True)
outData = _p.stdout.read().decode(locale.getpreferredencoding(False), "replace").strip()
```

This did not throw any errors. The output is the following:
���� ������ 26 14:10:22 MSK 2020

Third
-------

```
_p = subprocess.Popen("%s" % cmd, shell=True, env=environDict, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, close_fds=False, universal_newlines=True)
outData = _p.stdout.read().decode(encoding=locale.getpreferredencoding(False), error="replace").strip()
```

This did not work out due to:
`TypeError: 'error' is an invalid keyword argument for this function
`

**Comment by fstagni** [comment]
Igor, which python version?

**Comment by IgorPelevanyuk** [comment]
Python 2.7.13 (default, May  5 2020, 10:01:46) 
From dirac client directory

**Comment by fstagni** [comment]
Thanks. We would need to make sure to provide an implementation that is valid for the following python versions:
- 2.6.9
- 2.7.5
- 2.7.13
- 3.6.8
- 3.8

Would you mind to try out?

**Comment by IgorPelevanyuk** [comment]
2.6.9 - The following packages are not available from current channels
2.7.5 -  The following packages are not available from current channels

-------------------------------------
2.7.13 - OK
```
_p = subprocess.Popen("%s" % cmd, shell=True, env=environDict, stdout=subprocess.PIPE,
                                    stderr=subprocess.PIPE, close_fds=False, universal_newlines=True)

# standard output
outData = _p.stdout.read().decode(locale.getpreferredencoding(False), "replace").strip()
```

-------------------------------------
3.6.8 and 3.8 have no decode function. They successfully work with 
```
_p = subprocess.Popen("%s" % cmd, shell=True, env=environDict, stdout=subprocess.PIPE,
                                    stderr=subprocess.PIPE, close_fds=False, universal_newlines=True)
outData = _p.stdout.read().strip()
```

-------------------------------------

I would propose to make hotfix with the following code:
```
_p = subprocess.Popen("%s" % cmd, shell=True, env=environDict, stdout=subprocess.PIPE,
                                    stderr=subprocess.PIPE, close_fds=False, universal_newlines=True)

outData = _p.stdout.read().strip()
```
It works on both versions and does not break anything. On Python 2 it will print "\xd0\x9f\xd0\xbd \xd0\xb8\xd1\x8e\xd0\xbb" instead of unicode, but it will not crash (as it happens now).

---------------------------------------

I tested it with conda envs. The basic code is the following:
```
import subprocess
import locale
from pprint import pprint as pp

environDict = {
          "LC_TIME": "ru_RU.UTF-8",
          "LC_NAME": "ru_RU.UTF-8"
          }

cmd = "date"
_p = subprocess.Popen("%s" % cmd, shell=True, env=environDict, stdout=subprocess.PIPE,
                                    stderr=subprocess.PIPE, close_fds=False, universal_newlines=True)

#outData = _p.stdout.read().decode(locale.getpreferredencoding(False), "replace").strip()
outData = _p.stdout.read().strip()

pp(outData)
```

**Comment by fstagni** [comment]
Hi Igor,
fine, but I'd just be extra careful, so I created https://github.com/DIRACGrid/Pilot/pull/114

You guys can review and then I merge.
