### ISSUE TITLE
Pilot3 adds "pilot.cfg" on to user argument list

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/Pilot#120]
Hi,

While deploying pilot3 in production, one of our users noticed their argument list was now being corrupted... After a bit of poking around I found that "pilot.cfg" is always appended to the list of user arguments for JDL jobs (but not API jobs). We missed this during our initial tests as everything we run can (unfortunately) silently tolerate an extra argument.

I've tracked this behaviour down to this line of code:
https://github.com/DIRACGrid/Pilot/blob/e244e65f50d0c919f7cdc3775f75a2fa1fbc4cf7/Pilot/pilotCommands.py#L902

Why is this set? We've run our full GridPP test suite with this line commented out and all of the tests pass, but I can imagine that there must be a reason for setting this (for reference our inner CE is just InProcess)... Can we somehow get rid of this setting (by changing it to something else?) to fix this behaviour?

Just for complete clarity our test case for this is a JDL with:
Executable = "/usr/bin/echo";
Arguments = "Hello";

The Stdout contains `Hello pilot.cfg`.

Regards,
Simon

**Comment by fstagni** [comment]
@atsareg  suggests to set the DIRACSYSCONFIG env variable instead?

**Comment by fstagni** [comment]
Looking a bit into it: (re-)using the `DIRACSYSCONFIG` variable seems to me a bit dangerous: certain VOs might be running with option `--userEnvVariables DIRACSYSCONFIG:::/some/thing/conf.cfg` (see e.g. https://mail.google.com/mail/u/0/#search/DIRACSYSCONFIG/FMfcgxwHMjmHbMLktTDmFBjwXnTrwcXq).

I think instead it's better to add `pilot.cfg` only for DIRAC scripts. Please review https://github.com/DIRACGrid/DIRAC/pull/4836

**Comment by atsareg** [comment]
I am afraid DIRACGrid/DIRAC#4836 does not fix the problem. Mangling job arguments does not look an appropriate way. The configuration issues should rather be fixed with the configuration tools. We can update the configuration tools, for example, with the possibility to pass a list of config files in the  DIRACSYSCONFIG environment

**Comment by fstagni** [comment]
It's technically possible to pass a list of files in `DIRACSYSCONFIG`. Right now with the proposed solution we are making a quick fix just re-using the same tools that we have been using up to now.

**Comment by fstagni** [comment]
I added https://github.com/DIRACGrid/DIRAC/pull/4857 which is probably enough to satisfy one of the points above (pass a list of config files in the DIRACSYSCONFIG environment variable). 
Then I added https://github.com/DIRACGrid/Pilot/pull/122 for the Pilot and the test of both combined looks fine: https://jenkins-dirac.web.cern.ch/view/DIRAC/job/Pilot3_CVM4_pipeline/64/

Now, for the Pilot extensions: there *might* be the need to update something, e.g. for LHCb I had to make https://gitlab.cern.ch/lhcb-dirac/LHCbPilot/-/merge_requests/26 and it's being tested in https://jenkins-dirac.web.cern.ch/blue/organizations/jenkins/LHCbPilot3_CVM4_pipeline/detail/LHCbPilot3_CVM4_pipeline/128/pipeline

@sfayer if you want to set up the GridPP pilot test(s) in Jenkins, let me know I can help (they are really useful IMHO).

**Comment by fstagni** [comment]
Also https://jenkins-dirac.web.cern.ch/view/DIRAC/job/Pilot3_submitAndMatch/120/ passes so I marked the PRs above as "ready for review".

**Comment by sfayer** [comment]
We've tested this out and it seems to work fine on our GridPP preprod server (although see my comment on the #122 pull request, we don't tend to use that feature very much, but I think it may be slightly broken).

I don't think it's worth adding a GridPP Pilot test to Jenkins at the moment: We don't actually install the GridPP extension in the pilots at the moment, so the plain tests should be representative of whether it'll work in our set-up.

Regards,
Simon

**Comment by fstagni** [comment]
I believe this can be closed now.

**Comment by marianne013** [comment]
Simon just asked me to test this. I tested this this afternoon with the latest tagged version v7r1p24 which I hope would pick up the fix from the pilot repo. 
My JDL reads Arguments = "testarg1 testarg2";
and in my test script I do:
echo "All Arguments: $@"
and I get 
All Arguments: testarg1 testarg2 pilot.cfg

**Comment by fstagni** [comment]
What is in the JDL as Executable?

**Comment by marianne013** [comment]
```
[
Executable = "diractest.sh";
Arguments = "testarg1 testarg2";
StdOutput = "job.log";
StdError = "job.log";
InputSandbox = "diractest.sh";
OutputSandbox = "job.log";
Site = "LCG.UKI-LT2-IC-HEP.uk";
JobName = "DiracTest";
Platform = "AnyPlatform";

]
```

**Comment by fstagni** [comment]
Are you trying in a local test job, or going through the Job submission and so (via WMS)?

**Comment by marianne013** [comment]
I don't understand - this is a job submitted with dirac-wms-job-submit.

**Comment by fstagni** [comment]
Prob with this it will be fine: https://github.com/DIRACGrid/DIRAC/pull/4899

**Comment by fstagni** [comment]
Hi, did you try with the last DIRAC version? It's hopefully fully fixed by now.

**Comment by marianne013** [comment]
The last tag I could find was v7r1p43, but when I try and install a UI I get:
http://diracproject.web.cern.ch/diracproject/tars/release-DIRAC-v7r1p43.cfg does not exist
Which release did you have in mind ?

**Comment by fstagni** [comment]
Ah no v7r1p43 is a wrong tag @atsareg  please remove it!

Use v7r1p26.

**Comment by atsareg** [comment]
YEs, this was a result of misstag
      that stayed somehow propagated to the main repo.
    Now it is deleted, sorry about that.
    
    
      Cheers,
      Andrei
    
    
    
    On 26/01/2021 11:40, fstagni wrote:
    
    
      
      Ah no v7r1p43 is a wrong tag @atsareg
        please remove it!
      Use v7r1p26.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DIRACGrid/Pilot/issues/120#issuecomment-767457041",
"url": "https://github.com/DIRACGrid/Pilot/issues/120#issuecomment-767457041",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by marianne013** [comment]
Hi Federico, v7r1p26 seems to work correctly, thanks.
