### ISSUE TITLE
[v7r1] backport XRD_RUNFORKHANDLER fix to v7r1

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/Pilot#131]
Wrt https://github.com/DIRACGrid/DIRAC/issues/4616
As far as I can tell, the pilots in v7r1 are still using the dirac-install.py from the Pilot repo (rather than the management repo). It looks like the dirac-install scripts have diverged a bit, but would it be possible to to backport the XRD_RUNFORKHANDLER fix to this version as well? (I only just found this as I was trying to remove the "test the new code" override of our pilot configs.)
@chrisburr

**Comment by fstagni** [comment]
in #132
