### ISSUE TITLE
Merge devel branch?

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/Pilot#170]
Hi @fstagni,

Would it be possible to merge some of the older features from the devel branch out to production now? (I'm mainly interested in the rolling output patch, but there are some others in there too that are a few months old now).

Regards,
Simon

**Comment by fstagni** [comment]
I don't want to merge everything yet, so here there some single commits cherry-picked: https://github.com/DIRACGrid/Pilot/pull/171

Let me know if you want more.

**Comment by sfayer** [comment]
Thanks, that looks good to me.

Regards,
Simon
