### ISSUE TITLE
Logic in basic.yml prevents pytest from being run 

### ISSUE THREAD

**Issue by martynia** [DIRACGrid/Pilot#178]
There is a weird logic in this script. The line:
[https://github.com/DIRACGrid/Pilot/blob/3a837eccbf9f494d16e504699db1e32c3dc683d5/.github/workflows/basic.yml#L41
](https://github.com/DIRACGrid/Pilot/blob/3a837eccbf9f494d16e504699db1e32c3dc683d5/.github/workflows/basic.yml#L41)

will prevent `pytest` from being ever run. Not sure what was a reason behind this.

**Comment by fstagni** [comment]
I am not sure I understand. GitHub Action do run `pytest` (for 3 python versions), and I can run it in my setup. What do you mean?

**Comment by martynia** [comment]
So why are those tests skipped here:

https://github.com/DIRACGrid/Pilot/pull/176

The if statement listed  yields false:
`Run if [[ "3.9" == "2.7.13" ]] && [[ "pytest" == "CHECK=pylintPY3K ./runPylint.sh" ]]`

The statement looks like this:

`if [[ "${{ matrix.python }}" == "2.7.13" ]] && [[ "${{ matrix.command }}" == "CHECK=pylintPY3K ./runPylint.sh" ]]`

and will never run for python different from 2.7.13 and only for a command being` pylint`

Or am I looking at a wrong place ? There aren't seem to be any completed` pytest `tests in there.

**Comment by fstagni** [comment]
oh... now I see it!

Let me have a look!

**Comment by fstagni** [comment]
Have a look at #179
