### ISSUE TITLE
Recent pilot patch breaks command line tools in jobs

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/Pilot#188]
Hi,

Following the merge of #185, we've started getting errors from users where their jobs now fail to find the dirac.cfg when they run any dirac-* commands in their jobs script. As an emergency fix, I've swapped the GridPP production server over to a local branch without that commit, but it would be good to agree what the behaviour here should be (as we frequently seem to run into pilot.cfg/dirac.cfg problems!).

Tagging @marianne013 .

Regards,
Simon

**Comment by marianne013** [comment]
@fstagni @chrisburr What happened to testing stuff in dev first ?

**Comment by chrisburr** [comment]
I don't think we have any tests running `dirac-` commands within jobs. At some point we need a better supported way of enabling those workflows as I understand why people want to.

I think the fact this was working was just thanks to an accidental bug. Would setting `DIRACSYSCONFIG` be good enough for what your users need?

**Comment by marianne013** [comment]
The test is easy to add - I could just modify the multi-VO test. It's just weird, dirac-* not working within a DIRAC job, that's not something that's conceptually an easy sell.
I gather this is an LHCb issue at the moment (is anyone else using cvmfs ?). Can we put this on the next BiLD meeting agenda, so we can discuss this ?

**Comment by marianne013** [comment]
I just tried setting in Computing/CEDefaults:
ExtraPilotOptions = --userEnvVariables DIRACSYSCONFIG:::pilot.cfg
I dump my environment inside my jobs, but this variable doesn't show up (and obviously it still can't find the pilot commands). 
Is there a trick to it ?

**Comment by marianne013** [comment]
Apparently the trick is restarting it. 
Unfortunately it doesn't work, as the jobs doesn't know where pilot.cfg is (at least I assume that's what it is) and I can't really hardcode a path.

**Comment by marianne013** [comment]
Having had another look, I seem to be able to always find the pilot.cfg in $DIRACROOT/..
If this is indeed the case, can't the code have a look there all by itself, like the ageing bit of code it is ?

**Comment by fstagni** [comment]
`$DIRACROOT` is a python2 thing that we have completely eliminated from v8.1 (should have done in v8.0...): https://github.com/DIRACGrid/DIRAC/pull/6393

Effectively, what you want is the directory where the pilot script runs, which is effectively set by the CE. So, in the Pilot we should probably have something like

```python
        if self.pp.localConfigFile:
            os.environ["DIRACSYSCONFIG"] = os.path.realpath(self.pp.localConfigFile)
```

(cc @atsareg that proposed this)


Just for information: pilot.cfg is created in the "local directory" because it is a directory where the pilot script can write. If you are in the case described in https://github.com/DIRACGrid/Pilot/issues/166 (and addressed in https://github.com/DIRACGrid/Pilot/pull/187) then dirac.cfg would be in a CVMFS directory which is not writable.

**Comment by marianne013** [comment]
@fstagni Do you (or Andrei) have a tag so I can try it out ? We don't use cvmfs at the moment.

**Comment by fstagni** [comment]
Can you try https://github.com/DIRACGrid/Pilot/pull/192 ?

**Comment by sfayer** [comment]
Thanks for the patch... We tried it out but the variable didn't appear in the execution environment. We tried a slightly modified version that updated self.pp.installEnv instead at the same point and it appears that would work.

Regards,
Simon

**Comment by fstagni** [comment]
OK, can you commit your version or comment to my PR?

**Comment by sfayer** [comment]
Yes, it was fixed by this commit: https://github.com/DIRACGrid/Pilot/commit/a837c05af88d54c331ad9e59d044ff3bd149ca13

I'll close the issue...

Thanks,
Simon
